[package]
name = "natatorium"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.8"
owning_ref = "0.4"
stable_deref_trait = "1.1"
lock_api = { version = "0.2", features = ["owning_ref"]}
