[package]
name = "natatorium"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]

[dev-dependencies]
loom = { version = "0.2", git = "https://github.com/carllerche/loom" }
